---
title: "JAVA 기초 정리5"
excerpt: "대학교 수업중 메모한걸 정리하고 보완한 글. 예외처리(try/catch, throw) 에 대하여"
date: 2022-11-04
categories:
  - JAVA
tags:
  - JAVA
  - 예외처리
  - try/catch
  - throw
last_modified_at: 2022-11-04
---

# 예외처리 ( exception Handling)

하드웨어 문제나 자바 가상머신의 자원부족같은 심각한 문제는 프로그램으로 해결할 수 없으며  
가볍고 예상 가능한 에러는 예외처리로 사용자에게 전달할 수 있다.

<br>

모든상황에서 예외처리시 과부하가 걸릴수있기에 예외를 구분해두는데,  
일반의 exception은 개발자의 실수로 발생할 수도 있는 컴파일에서 못잡은 에러인 `일반예외`.

<br>

런타임의 exception은 error / exception으로 나뉘며  
error 자체는 `회복할수 없을정도`의 스택 오버플로우나(프로그램이 멈춤) 메모리가 부족한 아웃오브메모리 같은 경우이고  
exception은 `회복할수 있는것들`.. 예를 들어 산술연산관련 예외처리, null 포인터 exception등이 있다.  
즉 런타임에러는 컴파일에서 에러난 오타나 논리적인 오류인 `실행예외`으로 나뉘어진다.

<br>

### 1. 산술 예외 처리

| 오류 메시지           |          설명           |
| --------------------- | :---------------------: |
| `ArithmeticException` | 0에 관한 오류 (/byzero) |

<br>

### 2. 인덱스 범위 예외

| 오류 메시지                      |                       설명                        |
| -------------------------------- | :-----------------------------------------------: |
| `ArrayIndexOutofBoundsException` |       Array의 인덱스 범위를 벗어났다는 의미       |
| `NoSuchElementException`         | 더이상 꺼낼 토큰이 없어서 나오는 토큰 오류 메시지 |

<br>

NoSuchElementException 관련해서 사용하는 클래스와 메서드

`StringToltenizer` String을 토큰단위로 끊어주는 클래스

- 위의 클래스의 변수 이름.`hasmoreTokenS()` 다음 토큰이 존재하는지 확인하는 메서드, 있다면 true, 없다면 false
- 위의 클래스의 변수 이름.`nextToken()` 다음 토큰을 하나하나씩 꺼내주는 메서드

<br>

일반예외는 컴파일러가 확인하고 런타임예외는 따로 예외처리를 하던가 자바 가상머신에게 맡겨야만 한다.

<br>

## try/chach

`try{ 실행문 } catch (오류메시지 변수) { sysout("오류메시지"); }`

예외처리시 try/catch문으로 처리하지만 catch문이 없으면 try의 실행문이 실행되지 않으니 주의.

<br>

`try{ 실행문 }catch(error1 e){오류1}catch(error2 e){오류2}catch(error3 e){오류3}catch(Exception e){최종오류}Finally{ }`

<br>

이런식으로 겹쳐서 사용가능하다.  
마지막의 catch문의 `catch(Exception e)`의 Exception은 모든 예외의 조상이기에 모든 예외를 받는다는 뜻이기에 `catch문의 맨 마지막, finally의 바로 앞에` 있어야한다.  
오류메시지의 변수로 사용할수있는 메서드가 있다.

<Br>

- e.getMessage() - 시스템이 던지는 메시지를 볼수 있다.
- e.toString() - 에러의 메시지를 간단히 확인할수있게한다.
- e.printStackTrace() - `스택오류추적메서드.` 에러메시지의 근원지를 찾아 에러가 발생한곳을 알려준다

<br>

### Finally

try/catch문에서 `finally`는 예외에 상관없이 실행할수 있는 코드를 넣을수 있다.

<br>

catch문의 맨 마지막의 Finally 같은경우, try에서 일어난 일과 상관없이, 오류가 생겨도 finally 부분을 실행한다. `자원 해제`를 여기에 주로 구현한다.

<br>

## Throw

예외를 던질때 catch가 받아준다.

<br>

### 사용자 정의 예외의 예시

try부분에 Throw로 exception의 클래스의 객체를 던져 예외를 강제로 발생시키고  
catch부분에 예외처리 메시지를 getMessage()으로 출력하는 방법. `exception의 catch문의 에러메시지`가 `throw로 던진것`으로 된다.

<br>

### 발생 될 수 있는 예외 떠넘기기 예시

우리가 호출하는 메서드에서 예외를 main의 try/catch문으로 떠넘기는 방법이다.  
main의 try에서 호출된 메서드안에서 해결하지않고

<br>

`private static void SQ(string S) throws 발생될 예외 { 실행할 명령문 }`

<br>

으로 main의 try/catch문으로 떠넘긴다는 것.

<br>

<br>

---

<br>

<br>
